sudo: required

language: ruby

services:
  - docker

stages:
  - build
  - release
  - deploy

env:
  - CONTAINER_TEST_IMAGE=registry.gitlab.com/omerg/express-mongodb-base:$CI_BUILD_REF_NAME
  - CONTAINER_RELEASE_IMAGE=registry.heroku.com/express-mongodb-base/web

# safelist
branches:
  only:
  - master
  - stable

jobs:
  include:
  - stage: build
    script:
      - "Building Docker Image"
      - docker login -u $HEROKU_USERNAME -p $HEROKU_PRODUCTION_API_KEY registry.heroku.com
      - docker build -t $CONTAINER_TEST_IMAGE .
      - docker push $CONTAINER_TEST_IMAGE
  - stage: release
    script:
      - "Releasing to Heroku Container Registry"
      - docker login -u $HEROKU_USERNAME -p $HEROKU_PRODUCTION_API_KEY registry.heroku.com
      - docker pull $CONTAINER_TEST_IMAGE
      - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
      - docker push $CONTAINER_RELEASE_IMAGE
  - stage: deploy
    image: node:10.5.0-alpine
    script:
      - "Deploying to Heroku"
      - yarn global add heroku@7.4.11
      - export HEROKU_API_KEY=$HEROKU_PRODUCTION_API_KEY
      - heroku container:release web --app express-mongodb-base